version: '2'

services:
  mysql:
    image: mysql:5.6.26
    container_name: "mysqldb"
    environment:
     - MYSQL_ROOT_PASSWORD=admin
     - MYSQL_DATABASE=ordersdb
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    container_name: "postgresdb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  config-registry-server:
    build: ./config-registry-server
    ports:
      - "8888:8888"

  catalog-service:
    build: ./catalog-service
    ports:
      - "8181:8181"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "8383:8383"
    depends_on:
      - mysql

  customer-service:
    build: ./customer-service
    ports:
      - "8282:8282"
    depends_on:
      - postgres
      - order-service
